- name: Pull Redis image
  tags:
    - pull-system
    - pull-redis
  docker_image:
    name: redis
    tag: 4.0

- name: Create Redis volume
  tags:
    - pull-system
    - pull-redis
  docker_volume:
    name: redis

- name: Remove Redis volume
  tags:
    - never
    - clean-redis
  docker_volume:
    name: redis
    state: absent

- name: Start Redis container
  tags:
    - start-system
    - start-redis
  docker_container:
    name: redis
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis:/data

- name: Stop Redis container
  tags:
    - stop-system
    - stop-redis
  docker_container:
    name: redis
    state: absent
