- name: Pull Redis image
  tags:
    - pull-system
    - pull-redis
  docker_image:
    name: redis
    tag: 4.0

- name: Create Redis volume
  tags:
    - persist-system
    - persist-redis
  docker_volume:
    name: redis

- name: Remove Redis volume
  tags:
    - never
    - clean-redis
  docker_volume:
    name: redis
    state: absent

- name: Start Redis container
  tags:
    - start-system
    - start-redis
  docker_container:
    name: redis
    image: redis:latest
    memory: 128MB
    restart_policy: on-failure
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    log_driver: awslogs
    log_options:
      awslogs-region: us-west-2
      awslogs-group: datapunnet
      awslogs-stream: redis

- name: Stop Redis container
  tags:
    - stop-system
    - stop-redis
  docker_container:
    name: redis
    state: absent
