- name: Pull Nginx image
  tags:
    - pull-system
    - pull-nginx
  docker_image:
    name: nginx
    tag: 1.15

- name: Create Nginx volume
  tags:
    - pull-system
    - pull-nginx
    - persist-nginx
  docker_volume:
    name: assets

- name: Remove Nginx volume
  tags:
    - never
    - clean-nginx
  docker_volume:
    name: assets
    state: absent

- name: Configure Nginx
  tags:
    - configure-system
    - configure-nginx
  command: /bin/true
  delegate_to: 127.0.0.1
  notify: "configure production nginx"

- name: Start Nginx container
  tags:
    - start-system
    - start-nginx
  command: /bin/true
  delegate_to: 127.0.0.1
  notify: "start production nginx"

- name: Stop Nginx container
  tags:
    - stop-system
    - stop-nginx
  command: /bin/true
  delegate_to: 127.0.0.1
  notify: "stop production nginx"

- name: Reset Nginx container
  tags:
    - reset-system
    - reset-nginx
  command: /bin/true
  delegate_to: 127.0.0.1
  notify: "stop production nginx"
