- name: Pull Go image
  tags:
    - pull-system
    - pull-golang
  docker_image:
    name: erikperkins/golang_app

- name: Start Go container
  tags:
    - start-system
    - start-golang
  docker_container:
    name: golang
    image: erikperkins/golang_app
    command: /golang_app/golang_app
    restart_policy: on-failure
    ports:
      - 8002:80

- name: Stop Go app container
  tags:
    - stop-system
    - stop-golang
  docker_container:
    name: golang
    state: absent
