---
- hosts: all
  remote_user: ubuntu
  roles:
    - common

- hosts: storage
  roles:
    - mongo
    - postgres
    - rabbitmq
    - redis

- hosts: mnist
  roles:
    - blueberry

- hosts: timeseries
  roles:
    - cranberry

- hosts: main
  roles:
    - bayberry
    - cloudberry
    - nginx
    - certbot
