---
- hosts: all
  remote_user: ubuntu
  roles:
    - common

- hosts: main
  roles:
    - finch
    - nginx
    - rails

- hosts: mnist
  roles:
    - flask

- hosts: storage
  roles:
    - postgres
    - rabbitmq
    - redis
    - mongo

- hosts: timeseries
  roles:
    - iron
    - golang
    - phoenix
    - snap
