---
- hosts: all
  remote_user: ubuntu
  roles:
    - common

- hosts: main
  roles:
    - finch
    - nginx
    - phoenix

- hosts: mnist
  roles:
    - flask

- hosts: storage
  roles:
    - mongo
    - postgres
    - rabbitmq
    - redis

- hosts: timeseries
  roles:
    - iron
    - golang
    - snap
