---
- hosts: all
  remote_user: ubuntu
  roles:
    - common

- hosts: storage.datapun.net
  roles:
    - mongo
    - postgres
    - rabbitmq
    - redis

- hosts: mnist.datapun.net
  roles:
    - blueberry

- hosts: timeseries.datapun.net
  roles:
    - cranberry

- hosts: main.datapun.net
  roles:
    - bayberry
    - cloudberry
    - nginx
    - certbot
