---
- hosts: all
  remote_user: ubuntu
  roles:
    - common

- hosts: storage.datapun.net
  roles:
    - postgres
    - rabbitmq
    - redis

- hosts: mnist.datapun.net
  roles:
    - blueberry

- hosts: nlp.datapun.net
  roles:
    - cloudberry

- hosts: timeseries.datapun.net
  roles:
    - blackberry
    - cranberry

- hosts: main.datapun.net
  roles:
    - bayberry
    - certbot
    - nginx
