---
- hosts: all
  remote_user: ubuntu
  roles:
    - common

- hosts: storage
  roles:
    - postgres
    - rabbitmq
    - redis

- hosts: mnist
  roles:
    - blueberry

- hosts: nlp
  roles:
    - cloudberry

- hosts: timeseries
  roles:
    - blackberry
    - cranberry

- hosts: main
  roles:
    - bayberry
    - certbot
    - nginx
