---
- hosts: all
  gather_facts: false
  tasks:
    - name: Install Python
      tags:
        - test-connection
        - install-docker
        - install-python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python)

- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Update apt cache
      tags: install-docker
      apt:
        update_cache: yes
    - name: Install Docker
      tags: install-docker
      apt:
        name: docker.io
        state: present
    - name: Install pip
      tags: install-docker
      apt:
        name: python-pip
        state: present
    - name: Install virtualenv
      tags: install-docker
      apt:
        name: virtualenv
        state: present
    - name: Pip install docker
      tags: install-docker
      pip:
        name: docker
    - name: Add Docker group
      tags:
        - install-docker
        - add-docker-group
      group:
        name: docker
        state: present
    - name: Add user to Docker group
      tags:
        - install-docker
        - add-docker-group
      user:
        name: ubuntu
        groups: docker
        state: present
    - name: Rotate Docker logs
      tags: install-docker
      copy:
        src: '{{ inventory_dir }}/config/docker/daemon.json'
        dest: /etc/docker/daemon.json
    - name: Restart Docker daemon
      tags:
        - install-docker
        - add-docker-group
      service:
        name: docker
        state: restarted
