- name: Pull blueberry image
  tags:
    - pull-system
    - pull-blueberry
  docker_image:
    name: erikperkins/blueberry

- name: Start blueberry container
  tags:
    - start-system
    - start-blueberry
  docker_container:
    name: blueberry
    image: erikperkins/blueberry
    command: uwsgi --ini uwsgi.ini
    restart_policy: on-failure
    ports:
      - 80:80
    log_driver: awslogs
    log_options:
      awslogs-region: us-west-2
      awslogs-group: datapunnet
      awslogs-stream: blueberry

- name: Stop blueberry container
  tags:
    - stop-system
    - stop-blueberry
  docker_container:
    name: blueberry
    state: absent
