- name: Pull RabbitMQ image
  tags:
    - pull-system
    - pull-rabbitmq
  docker_image:
    name: rabbitmq
    tag: 3.7-management

- name: Create RabbitMQ volume
  tags:
    - persist-system
    - persist-rabbitmq
  docker_volume:
    name: rabbitmq

- name: Remove RabbitMQ volume
  tags:
    - never
    - clean-system
    - clean-rabbitmq
  docker_volume:
    name: rabbitmq
    state: absent

- name: Start RabbitMQ container
  tags:
    - start-system
    - start-rabbitmq
  docker_container:
    name: rabbitmq
    image: rabbitmq:3.7-management
    restart_policy: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    log_driver: awslogs
    log_options:
      awslogs-region: us-west-2
      awslogs-group: datapunnet
      awslogs-stream: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq/

- name: Stop RabbitMQ container
  tags:
    - stop-system
    - stop-rabbitmq
  docker_container:
    name: rabbitmq
    state: absent
