- hosts: storage
  remote_user: ubuntu
  tasks:
    - import_tasks: postgres.yml
    - import_tasks: redis.yml
    - import_tasks: rabbitmq.yml

    - name: SSH agent forwarding
      tags:
        - pull-postgres
      local_action:
        module: lineinfile
        path: ~/.ssh/config
        regexp: 'Host [\d]+\.[\d]+\.[\d]+\.[\d]+'
        line: 'Host {{ inventory_hostname }}'

    - name: Deploy PostgreSQL configuration
      tags:
        - pull-postgres
      synchronize:
        src: '{{ inventory_dir }}/config/postgres'
        dest: ~/
        existing_only: false
        private_key: ~/.ssh/id_rsa
      notify: Restart PostgreSQL

    - name: Create PostgreSQL volume
      tags:
        - pull-postgres
      docker_volume:
        name: postgres

  handlers:
    - name: Restart PostgreSQL
      docker_container:
        name: postgres
        restart: yes
