- name: Pull Finch image
  tags:
    - pull-system
    - pull-finch
  docker_image:
    name: erikperkins/finch_app

- name: Remove Finch image
  tags:
    - remove-system
    - remove-finch
  docker_image:
    name: erikperkins/finch_app
    state: absent

- name: Start Finch container
  tags:
    - start-system
    - start-finch
  docker_container:
    name: finch
    image: erikperkins/finch_app
    restart_policy: on-failure
    hostname: finch
    env:
      FINCH_ENV: production
    ports: 1025:80

- name: Stop Finch container
  tags:
    - stop-system
    - stop-finch
  docker_container:
    name: finch
    state: absent
