- name: Remove bayberry image for reset
  docker_image:
    name: erikperkins/bayberry
    state: absent
  listen: "remove bayberry image"
  notify: "pull bayberry image"

- name: Pull bayberry image for reset
  docker_image:
    name: erikperkins/bayberry
  listen: "pull bayberry image"
  notify: "start bayberry container"

- name: Start bayberry container for reset
  tags:
    - start-system
    - start-bayberry
  docker_container:
    name: bayberry
    image: erikperkins/bayberry
    entrypoint: /bayberry/assets.sh
    command: mix phx.server
    env:
      MIX_ENV: prod
      BAYBERRY_SECRET_KEY_BASE: "{{ lookup('env', 'BAYBERRY_SECRET_KEY_BASE') }}"
      BAYBERRY_USERNAME: "{{ lookup('env', 'BAYBERRY_USERNAME') }}"
      BAYBERRY_PASSWORD: "{{ lookup('env', 'BAYBERRY_PASSWORD') }}"
      BAYBERRY_DATABASE: "{{ lookup('env', 'BAYBERRY_DATABASE') }}"
      TWITTER_CONSUMER_KEY: "{{ lookup('env', 'TWITTER_CONSUMER_KEY') }}"
      TWITTER_CONSUMER_SECRET: "{{ lookup('env', 'TWITTER_CONSUMER_SECRET') }}"
      TWITTER_ACCESS_TOKEN: "{{ lookup('env', 'TWITTER_ACCESS_TOKEN') }}"
      TWITTER_ACCESS_SECRET: "{{ lookup('env', 'TWITTER_ACCESS_SECRET') }}"
    restart_policy: on-failure
    volumes:
      - assets:/bayberry/priv/static/
    ports:
      - 1024:80
  listen: "start bayberry container"
