- name: Push bayberry image
  command: docker push erikperkins/bayberry
  delegate_to: 127.0.0.1
  listen: "push bayberry"
  notify: "stop bayberry"

- name: Stop bayberry
  listen: "stop bayberry"
  when: procedure.stdout in ['stop', 'reset', 'destroy']
  notify: "remove bayberry"
  docker_container:
    name: bayberry
    state: absent

- name: Remove bayberry
  listen: "remove bayberry"
  when: procedure.stdout in ['remove', 'reset', destroy]
  notify: "pull bayberry"
  docker_image:
    name: erikperkins/bayberry
    state: absent

- name: Pull bayberry image
  listen: "pull bayberry"
  when: procedure.stdout in ['pull', 'create', 'reset']
  notify:
    - "start bayberry"
  docker_image:
    name: erikperkins/bayberry

- name: Start bayberry
  listen: "start bayberry"
  when: procedure.stdout in ['start', 'create', 'reset']
  docker_container:
    name: bayberry
    image: erikperkins/bayberry
    entrypoint: /bayberry/entrypoint.sh
    command: mix phx.server
    env:
      MIX_ENV: prod
      BAYBERRY_SECRET_KEY_BASE: "{{ bayberry_secret_key_base }}"
      BAYBERRY_USERNAME: "{{ bayberry_username }}"
      BAYBERRY_PASSWORD: "{{ bayberry_password }}"
      BAYBERRY_DATABASE: "{{ bayberry_database }}"
      DATAPUNNET_ADMIN_PASSWORD: "{{ datapunnet_admin_password }}"
      TWITTER_CONSUMER_KEY: "{{ twitter_consumer_key }}"
      TWITTER_CONSUMER_SECRET: "{{ twitter_consumer_secret }}"
      TWITTER_ACCESS_TOKEN: "{{ twitter_access_token }}"
      TWITTER_ACCESS_SECRET: "{{ twitter_access_secret }}"
    restart_policy: on-failure
    volumes:
      - assets:/bayberry/priv/static/
    ports:
      - 1024:80
    log_driver: awslogs
    log_options:
      awslogs-region: us-west-2
      awslogs-group: datapunnet
      awslogs-stream: bayberry
