- name: Push bayberry image for reset
  command: docker push erikperkins/bayberry
  delegate_to: 127.0.0.1
  listen: "push bayberry image"
  notify: "remove bayberry container"

- name: Remove bayberry container for reset
  docker_container:
    name: bayberry
    state: absent
  listen: "remove bayberry container"
  notify: "remove bayberry image"

- name: Remove bayberry image for reset
  docker_image:
    name: erikperkins/bayberry
    state: absent
  listen: "remove bayberry image"
  notify: "pull bayberry image"

- name: Pull bayberry image for reset
  docker_image:
    name: erikperkins/bayberry
  listen: "pull bayberry image"
  notify: "start bayberry container"

- name: Start bayberry container for reset
  docker_container:
    name: bayberry
    image: erikperkins/bayberry
    entrypoint: /bayberry/entrypoint.sh
    command: mix phx.server
    env:
      MIX_ENV: prod
      BAYBERRY_SECRET_KEY_BASE: "{{ bayberry_secret_key_base }}"
      BAYBERRY_USERNAME: "{{ bayberry_username }}"
      BAYBERRY_PASSWORD: "{{ bayberry_password }}"
      BAYBERRY_DATABASE: "{{ bayberry_database }}"
      DATAPUNNET_ADMIN_PASSWORD: "{{ datapunnet_admin_password }}"
      TWITTER_CONSUMER_KEY: "{{ twitter_consumer_key }}"
      TWITTER_CONSUMER_SECRET: "{{ twitter_consumer_secret }}"
      TWITTER_ACCESS_TOKEN: "{{ twitter_access_token }}"
      TWITTER_ACCESS_SECRET: "{{ twitter_access_secret }}"
    restart_policy: on-failure
    volumes:
      - assets:/bayberry/priv/static/
    ports:
      - 1024:80
    log_driver: awslogs
    log_options:
      awslogs-region: us-west-2
      awslogs-group: datapunnet
      awslogs-stream: bayberry
  listen: "start bayberry container"
