- name: Pull bayberry image
  tags:
    - pull-system
    - pull-bayberry
  docker_image:
    name: erikperkins/bayberry

- name: Remove bayberry image
  tags:
    - remove-system
    - remove-bayberry
  docker_image:
    name: erikperkins/bayberry
    state: absent

- name: Start bayberry container
  tags:
    - start-system
    - start-bayberry
  command: /bin/true
  delegate_to: 127.0.0.1
  notify: "start bayberry container"

- name: Stop bayberry container
  tags:
    - stop-system
    - stop-bayberry
  docker_container:
    name: bayberry
    state: absent

- name: Reset bayberry application
  tags:
    - never
    - reset-system
    - reset-bayberry
  command: /bin/true
  delegate_to: 127.0.0.1
  notify: "push bayberry image"
