- name: Pull bayberry image
  tags:
    - pull-system
    - pull-bayberry
  command: /bin/echo pull
  register: procedure
  delegate_to: 127.0.0.1
  notify: "pull bayberry"

- name: Remove bayberry image
  tags:
    - stop-system
    - remove-bayberry
  command: /bin/echo remove
  register: procedure
  delegate_to: 127.0.0.1
  notify: "remove bayberry"

- name: Start bayberry container
  tags:
    - start-system
    - start-bayberry
  command: /bin/echo start
  register: procedure
  delegate_to: 127.0.0.1
  notify: "start bayberry"

- name: Stop bayberry container
  tags:
    - stop-system
    - stop-bayberry
  command: /bin/echo stop
  register: procedure
  delegate_to: 127.0.0.1
  notify: "stop bayberry"

- name: Create bayberry
  tags:
    - create-system
    - create-bayberry
  command: /bin/echo create
  register: procedure
  delegate_to: 127.0.0.1
  notify: "pull bayberry"

- name: Destroy bayberry
  tags:
    - destroy-system
    - detroy-bayberry
  command: /bin/echo destroy
  register: procedure
  delegate_to: 127.0.0.1
  notify: "stop bayberry"

- name: Reset bayberry container
  tags:
    - reset-system
    - reset-bayberry
  command: /bin/echo reset
  register: procedure
  delegate_to: 127.0.0.1
  notify: "push bayberry"
