- name: Pull cranberry image
  tags:
    - pull-system
    - pull-cranberry
  docker_image:
    name: erikperkins/cranberry

- name: Remove cranberry image
  tags:
    - remove-system
    - remove-cranberry
  docker_image:
    name: erikperkins/cranberry
    state: absent

- name: Start cranberry container
  tags:
    - start-system
    - start-cranberry
  docker_container:
    name: cranberry
    image: erikperkins/cranberry
    command: .cabal-sandbox/bin/cranberry -p 80
    env:
      REDIS_HOST: "{{ redis_host }}"
      REDIS_DATABASE: "{{ redis_database }}"
      REDIS_PASSWORD: "{{ redis_password }}"
    restart_policy: on-failure
    ports:
      - 80:80
    log_driver: awslogs
    log_options:
      awslogs-region: us-west-2
      awslogs-group: datapunnet
      awslogs-stream: cranberry

- name: Stop cranberry app container
  tags:
    - stop-system
    - stop-cranberry
  docker_container:
    name: cranberry
    state: absent
