- name: Test connection
  tags:
    - never
    - ping
  ping:

- name: SSH agent forwarding
  tags:
    - never
    - github
  local_action:
    module: lineinfile
    path: ~/.ssh/config
    regexp: 'Host [\d]+\.[\d]+\.[\d]+\.[\d]+'
    line: 'Host {{ inventory_hostname }}'

- name: Pull Data Punnet repository
  tags:
    - never
    - github
  git:
    accept_hostkey: yes
    dest: ~/datapunnet
    repo: git@github.com:erikperkins/datapunnet
