- name: Pull Go image
  tags:
    - pull-system
    - pull-mulberry
  docker_image:
    name: erikperkins/mulberry

- name: Start Go container
  tags:
    - start-system
    - start-mulberry
  docker_container:
    name: mulberry
    image: erikperkins/mulberry
    command: /mulberry_app/mulberry_app
    restart_policy: on-failure
    ports:
      - 8002:80

- name: Stop Go app container
  tags:
    - stop-system
    - stop-mulberry
  docker_container:
    name: mulberry
    state: absent
