- name: Pull PostgreSQL image
  tags:
    - pull-system
    - pull-postgres
  docker_image:
    name: postgres
    tag: 11

- name: Create PostgreSQL volume
  tags:
    - pull-system
    - pull-postgres
  docker_volume:
    name: postgres

- name: Configure PostgreSQL
  tags:
    - configure-system
    - configure-postgres
  synchronize:
    src: '{{ inventory_dir }}/roles/postgres/files'
    dest: ~/
    existing_only: false
    private_key: ~/.ssh/id_rsa
  notify: Restart PostgreSQL

- name: Start PostgreSQL container
  tags:
    - start-system
    - start-postgres
  docker_container:
    name: postgres
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data/
      - /home/ubuntu/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

- name: Stop PostgreSQL container
  tags:
    - stop-system
    - stop-postgres
  docker_container:
    name: postgres
    state: absent
