- name: Pull PostgreSQL image
  tags:
    - pull-system
    - pull-postgres
  docker_image:
    name: postgres
    tag: 11

- name: Create PostgreSQL volume
  tags:
    - persist-system
    - persist-postgres
  docker_volume:
    name: postgres

- name: Remove PostgreSQL volume
  tags:
    - never
    - clean-postgres
  docker_volume:
    name: postgres
    state: absent

- name: Configure PostgreSQL
  tags:
    - configure-system
    - configure-postgres
  synchronize:
    src: '{{ inventory_dir }}/roles/postgres/files/'
    dest: ~/postgres
    existing_only: no
    recursive: yes
    perms: yes
    private_key: ~/.ssh/id_rsa

- name: Start PostgreSQL container
  tags:
    - start-system
    - start-postgres
  docker_container:
    name: postgres
    image: postgres:11
    memory: 128MB
    restart_policy: on-failure
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    volumes:
      - /home/ubuntu/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    log_driver: awslogs
    log_options:
      awslogs-region: us-west-2
      awslogs-group: datapunnet
      awslogs-stream: postgres

- name: Stop PostgreSQL container
  tags:
    - stop-system
    - stop-postgres
  docker_container:
    name: postgres
    state: stopped
